version: "3.8"

services:

  api:
    image: dvasilevich/electronics_shop:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file: .env

  migrations:
    image: dvasilevich/electronics_shop:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    command: python manage.py migrate

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
