# Generated by Django 4.0.1 on 2023-05-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=80, null=True, verbose_name='Улица')),
                ('house', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('product_model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=80, null=True, verbose_name='Улица')),
                ('house', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('credit', models.IntegerField(verbose_name='Задолженность')),
                ('products', models.ManyToManyField(to='shops.Products', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.factorystore', verbose_name='Поставщики')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.AddField(
            model_name='factorystore',
            name='products',
            field=models.ManyToManyField(to='shops.Products', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=80, null=True, verbose_name='Улица')),
                ('house', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(verbose_name='Задолженность')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('products', models.ManyToManyField(to='shops.Products', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Предприниматель',
                'verbose_name_plural': 'Предприниматели',
                'ordering': ['created'],
            },
        ),
    ]
